# Generated by Django 3.0.3 on 2020-02-23 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislike',
            field=models.ManyToManyField(related_name='disliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posts',
            name='report',
            field=models.ManyToManyField(related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
