# Generated by Django 3.0.3 on 2020-02-23 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userposts', '0002_auto_20200223_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='disliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='reported_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
