# Generated by Django 3.0.3 on 2020-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userposts', '0003_auto_20200223_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_status',
            field=models.BooleanField(default=True),
        ),
    ]
